spring.application.name=FileProcessingApp

aws.s3.access_key = AKIAU2TZH622BCE4NC26
aws.s3.secret_key = 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
aws.s3.region = ap-south-1

aws.s3.bucket_name = file-app-s3-bucket
